/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillasIndexRouteImport } from './routes/villas.index'
import { Route as VillasSlugRouteImport } from './routes/villas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasIndexRoute = VillasIndexRouteImport.update({
  id: '/villas/',
  path: '/villas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasSlugRoute = VillasSlugRouteImport.update({
  id: '/villas/$slug',
  path: '/villas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/villas': typeof VillasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/villas/$slug': typeof VillasSlugRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/villas/$slug' | '/villas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/villas/$slug' | '/villas'
  id: '__root__' | '/' | '/villas/$slug' | '/villas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VillasSlugRoute: typeof VillasSlugRoute
  VillasIndexRoute: typeof VillasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/': {
      id: '/villas/'
      path: '/villas'
      fullPath: '/villas/'
      preLoaderRoute: typeof VillasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$slug': {
      id: '/villas/$slug'
      path: '/villas/$slug'
      fullPath: '/villas/$slug'
      preLoaderRoute: typeof VillasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VillasSlugRoute: VillasSlugRoute,
  VillasIndexRoute: VillasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
